{% set version = "2.0" %}
package:
  name: bwa-mem2
  version: {{ version }}

source:
  - url: https://github.com/bwa-mem2/bwa-mem2/archive/v{{ version}}.tar.gz
    sha256: 2c81ad44b58af6fba2519beefd5ac1c63b81611fda522c98b68faf54f18fa445    
  - git_url: https://github.com/intel/safestringlib
    folder: ext/safestringlib
#  url: https://github.com/bwa-mem2/bwa-mem2/releases/download/v2.0/bwa-mem2-{{ version }}_x64-linux.tar.bz2
#  sha256: 15df322cdb6ff3d12105ee1e263449a9dd7698617b641167bca575d93361489f

#ext/safestringlib

build:
  number: 0
  noarch: generic

requirements:
  host:
    - zlib
    - libgcc
#  run:

test:
  commands:
    - bwa-mem2 version

about:
  home: https://github.com/bwa-mem2/bwa-mem2
  license: MIT
  summary: The next version of bwa-mem 

#extra:
#  skip-lints:
#    - should_use_compilers
