{% set name = "phispy" %}
{% set ucname = "PhiSpy" %}
{% set version = "4.1.11" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ ucname }}-{{ version }}.tar.gz"
  sha256: "c5ebbc241511c74a4502ac226bda40ffc543727d707f233ef5083aa1ba4c68b9"

build:
  number: 0
  skip: True  # [py27]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv "

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - biopython >=1.74
    - numpy >=1.17.0
    - python
    - scikit-learn >=0.21.3

test:
  imports:
    - PhiSpyModules
  commands:
    - PhiSpy.py -v

about:
  home: "https://github.com/linsalrob/PhiSpy"
  license: "MIT License"
  license_family: "MIT"
  summary: "Prophage finder using multiple metrics"
  doc_url: "https://github.com/linsalrob/PhiSpy/blob/master/README.md"
  dev_url: "https://github.com/linsalrob/PhiSpy/"

extra:
  recipe-maintainers:
    - linsalrob
  identifiers:
    - doi:10.5281/zenodo.3475717
